repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        description: Format the code
        entry: poetry run ruff format .
        pass_filenames: false # run once per commit rather than file
        language: system
    -   id: sort-imports
        name: sort-imports
        description: Keep imports in a nice sorted order
        entry: ruff check --select I --fix
        pass_filenames: false
        language: system
    # -   id: mypy
    #     name: mypy
    #     description: Verify types statically
    #     entry: poetry run mypy src
    #     pass_filenames: false
    #     language: system
    # -   id: pylint
    #     name: pylint_core
    #     entry: poetry run pylint src
    #     files: src/.*\.py$
    #     language: system
    #     types: [ python ]
    #     verbose: false
    #     args:
    #       - --fail-under=9
    -   id: pytest
        name: pytest
        description: Run Python tests
        entry: poetry run pytest
        pass_filenames: false
        language: system
    -   id: poetry
        name: poetry
        description: Validates the content of the pyproject.toml file and its consistency with the poetry.lock file
        entry: poetry check
        pass_filenames: false
        language: system
    -   id: poetry-export-service
        name: poetry-export
        description: Exports requirements.txt file for docker container with service and web dependencies
        entry: poetry export
        args: [ "--with", "dev,training,web,service", "-o", "requirements.txt" ]
        pass_filenames: false
        language: system
