services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8000:8000
    environment:
      - LM_API_BASE_URL=http://host.docker.internal:5001/v1
    volumes:
      - ./:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge
